package com.toydbbackend.springbootserver.controller;

import org.slf4j.LoggerFactory;
import org.slf4j.Logger;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;

import com.toydbbackend.springbootserver.model.Book;
import com.toydbbackend.springbootserver.repository.BookRepository;

import java.util.List;
import java.util.Optional;

@Controller // This means that this class is a Controller
@RequestMapping(path = "/book") // This means URL's start with /book (after Application path)

public class BookController {
    private static final Logger log = LoggerFactory.getLogger(BookController.class);
    @Autowired // This means to get the bean called bookRepository
               // Which is auto-generated by Spring, we will use it to handle the data
    private BookRepository bookRepository;

    @GetMapping(path = "/get")
    public ResponseEntity<Iterable<Book>> getAllBooks(@RequestParam(required = false) String bookID) {
        if (bookID != null && !bookID.isEmpty()) {
            List<Book> filteredBooks = bookRepository.findByBookID(bookID);
            if (filteredBooks.isEmpty()) {
                return ResponseEntity.notFound().build();
            } else {
                return ResponseEntity.ok(filteredBooks);
            }
        } else {
            Iterable<Book> allBooks = bookRepository.findAll();
            return ResponseEntity.ok(allBooks);
        }
    }

    @PostMapping(path = "/add") // Map ONLY POST Requests
    public ResponseEntity<?> addNewBook(@RequestBody Book newBook) {
        try {
            Optional<Book> existingBook = bookRepository.findById(newBook.getBookID());
            if (existingBook.isPresent()) {
                return ResponseEntity.badRequest().body("Error: Duplicate book entry");
            }
            Book savedBook = bookRepository.save(newBook); // contructor in Book.java is used here
            return ResponseEntity.status(HttpStatus.CREATED).body(savedBook);
        } catch (DataIntegrityViolationException e) {
            return ResponseEntity.badRequest().body("Error: Duplicate book entry");
        } catch (Exception e) {
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).build();
        }
    }

    @PutMapping(path = "/update/{bookID}")
    public ResponseEntity<?> updateBook(@PathVariable("bookID") String bookID, @RequestBody Book newBook) {
        try {
            Optional<Book> existingBook = bookRepository.findById(newBook.getBookID());
            if (existingBook.isPresent()) {
                Book savedBook = bookRepository.save(newBook);
                return ResponseEntity.ok(savedBook);
            } else {
                return ResponseEntity.notFound().build();
            }
        } catch (Exception e) {
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).build();
        }
    }

}
